// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChofIoCMsxvjxdISyfGQpBICu1ZFXn6xg',
    appId: '1:35348409332:web:19a1191064b8e359d767a1',
    messagingSenderId: '35348409332',
    projectId: 'tictact-a37a5',
    authDomain: 'tictact-a37a5.firebaseapp.com',
    databaseURL: 'https://tictact-a37a5-default-rtdb.firebaseio.com',
    storageBucket: 'tictact-a37a5.appspot.com',
    measurementId: 'G-DXBX98VV9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLxGqNvlmTNbFHrQNGRMerLRZsOFrA1lk',
    appId: '1:133784169535:android:aeacf18d3df5109827dc8a',
    messagingSenderId: '133784169535',
    projectId: 'tic-tac-toe-897db',
    databaseURL: 'https://tic-tac-toe-897db-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-897db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG1npSvJM4PWSby2-4g749zVtDuVwOxU0',
    appId: '1:133784169535:ios:e47d2c677de6d28c27dc8a',
    messagingSenderId: '133784169535',
    projectId: 'tic-tac-toe-897db',
    databaseURL: 'https://tic-tac-toe-897db-default-rtdb.firebaseio.com',
    storageBucket: 'tic-tac-toe-897db.appspot.com',
    androidClientId: '133784169535-0784r27ho55vhobim4a467q74uch9242.apps.googleusercontent.com',
    iosClientId: '133784169535-rbcl4hilanc3k4jc9j9t6q7vdc5a5kio.apps.googleusercontent.com',
    iosBundleId: 'com.tictac.wrteam.TicTacToe',
  );

}